import { Inter } from "next/font/google";
import Navbar from "../components/navbar/navbar";
import Footer from "@/components/footer/footer";
import About from "./about/page.js";
import "../styles/modern-normalize.css";
import "../styles/globals.css";
import "../styles/utils.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
